%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#     with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 4 -*-
---

on:
    push:
        branches:
            -   '*'

jobs:
    job_npm_test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                ver:
                  - { node:  8 }
                  - { node: 16 }
                  - { node: 20 }

        env:
            nodejs_version: ${{ matrix.ver.node }}

        steps:
          - uses: actions/checkout@v4
          - uses: mk-pmb/github-ci-util-2405-pmb/act/install@experimental
            with:
                nodejs_version: ${{ matrix.ver.node }}

          - run: ghciu npm install .

          - run: ghciu ./.github/adjust_ci_for_ancient_nodejs.sh
            if: 'fromJSON(matrix.ver.node) < 12'

          - name: npm test
            run: >
                ghciu npm test &> >(ghciu-stepsumm-dump-textblock)


...
